### PR TITLE
Adding Athena team members

### PR DESCRIPTION
**Pull request by amandavarella**
Adding Athena team members

### CODE REVIEW

**Comment by AeroCross** [comment]
Shouldn't Emily K. be there as well?

**Comment by asellitt** [comment]
what about Hermes?

**Comment by amandavarella** [comment]
Nice catch @AeroCross fixed!

**Comment by amandavarella** [comment]
@asellitt Mark is still to send Hermes team members. We can add later.

**Comment by AeroCross** [comment]
There's this person called Hermes the Illuminated in Venezuela which reads the horoscope for people in the mornings and that's the only thing I can think of when I read "Hermes"

Hermes el Iluminado

**Pull request merged**
